
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers"

import Player  from "../app/components/Player"
import "./globals.css";
export const metadata = {
  title: {
    template: "%s | IPlayMusic", 
    default: "IPlayMusic"
  },
  description: "Generated by create next app",
};



export default async function RootLayout({children}){
   const cookieStore = await cookies()
        const access_token = cookieStore.get("ipm_acces_token")
    

    
    return(
        <html>
            <body>
              <Player uri="" token={access_token} >
                {children}
                </Player>
            </body>
        </html>
    )
}